# Generated by Django 5.2.7 on 2025-11-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Дом, Работа', max_length=100, verbose_name='Название адреса')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира/Офис')),
                ('comment', models.TextField(blank=True, help_text='Например: домофон не работает', verbose_name='Комментарий к адресу')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
