# Generated by Django 6.0.1 on 2026-01-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_cd4531_idx',
            old_name='products_produc_categor_c873ce_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_price_9b1a5f_idx',
            old_name='products_produc_price_b0210f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_avai_c23034_idx',
            old_name='products_produc_is_avai_19b660_idx',
        ),
    ]
